// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5b6DkenNuEcaKp6LFA4o1ckBeLZy8qCw',
    appId: '1:1064069449864:web:d9222295b3d76ac6d4b73d',
    messagingSenderId: '1064069449864',
    projectId: 'shoppy-6148b',
    authDomain: 'shoppy-6148b.firebaseapp.com',
    storageBucket: 'shoppy-6148b.appspot.com',
    measurementId: 'G-VHSMG5VD2Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCK-4eBrPdUTbOcIG2KlB02J8MlqNM1uSI',
    appId: '1:1064069449864:android:38b6371d8f1f0bddd4b73d',
    messagingSenderId: '1064069449864',
    projectId: 'shoppy-6148b',
    storageBucket: 'shoppy-6148b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoPDyPmWV8BMAjN8wK8azASSWumChCyQA',
    appId: '1:1064069449864:ios:b537ced4c7c70e73d4b73d',
    messagingSenderId: '1064069449864',
    projectId: 'shoppy-6148b',
    storageBucket: 'shoppy-6148b.appspot.com',
    iosBundleId: 'com.example.shoppy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoPDyPmWV8BMAjN8wK8azASSWumChCyQA',
    appId: '1:1064069449864:ios:cf2ce9ebb6d48767d4b73d',
    messagingSenderId: '1064069449864',
    projectId: 'shoppy-6148b',
    storageBucket: 'shoppy-6148b.appspot.com',
    iosBundleId: 'com.example.shoppy.RunnerTests',
  );
}
